import { StyleSheet } from "react-native";

export const inspectionStyles = StyleSheet.create({
  // layout
  container: { gap: 12, paddingBottom: 40 },
  empty: { flex: 1, backgroundColor: '#F8FAFC', padding: 16 },
  emptyBack: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 2, paddingVertical: 8, paddingRight: 12 },
  emptyBackText: { color: '#0F172A', fontSize: 15, fontWeight: '600' },
  emptyCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  emptyTitle: { color: '#0F172A', fontSize: 18, fontWeight: '700' },

  // header
  header: { backgroundColor: '#4a5565', paddingHorizontal: 20, paddingBottom: 20, gap: 10 },
  headerBack: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', marginLeft: -4, marginBottom: 2, gap: 2 },
  headerBackText: { color: 'rgba(255,255,255,0.9)', fontSize: 15, fontWeight: '600' },
  headerRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  headerInfo: { flex: 1, gap: 4 },
  headerKicker: { color: 'rgba(255,255,255,0.7)', fontSize: 12, fontWeight: '700' },
  headerAptNumber: { color: '#FFFFFF', fontSize: 34, fontWeight: '900', lineHeight: 38 },
  headerNotes: { color: 'rgba(255,255,255,0.75)', fontSize: 13, lineHeight: 18 },
  headerProgressCircle: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.18)', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 12 },
  headerProgressValue: { color: '#FFFFFF', fontSize: 30, fontWeight: '900' },
  headerProgressLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 11, fontWeight: '600' },
  headerBar: { backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: 999, height: 6, overflow: 'hidden' },
  headerBarFill: { backgroundColor: 'rgba(255,255,255,0.8)', height: '100%', borderRadius: 999 },
  headerMeta: { flexDirection: 'row', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  headerMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  headerMetaText: { color: 'rgba(255,255,255,0.8)', fontSize: 12, fontWeight: '600' },
  statusPill: { backgroundColor: '#FFFFFF', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  statusPillText: { fontSize: 11, fontWeight: '900' },

  // visit banner
  visitBannerOpen: { backgroundColor: '#EFF6FF', borderColor: '#BFDBFE', borderWidth: 1, borderRadius: 14, marginHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 14, gap: 10 },
  visitBannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  visitPulse: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#2563EB' },
  visitBannerTitle: { color: '#1D4ED8', fontSize: 13, fontWeight: '800' },
  visitBannerSub: { color: '#60A5FA', fontSize: 11, marginTop: 1 },
  visitFinishBtn: { backgroundColor: '#2563EB', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 9 },
  visitFinishBtnText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  visitBannerNew: { backgroundColor: '#FFFFFF', borderColor: '#DBEAFE', borderWidth: 1, borderRadius: 14, marginHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 8, padding: 14 },
  visitBannerNewText: { color: '#2563EB', fontSize: 13, fontWeight: '700' },

  // kpi
  kpiRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16 },
  kpiCard: { flex: 1, backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, padding: 12, alignItems: 'center', gap: 4 },
  kpiValue: { fontSize: 22, fontWeight: '900', color: '#0F172A' },
  kpiLabel: { color: '#64748B', fontSize: 10, fontWeight: '700', textAlign: 'center' },

  // tab bar
  tabBarWrap: { justifyContent: 'center' },
  tabBar: { flexDirection: 'row', gap: 6, paddingHorizontal: 16, paddingBottom: 2 },
  tabArrow: { position: 'absolute', top: '50%', marginTop: -15, width: 30, height: 30, borderRadius: 15, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center', shadowColor: '#0F172A', shadowOpacity: 0.12, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 3 },
  tabArrowLeft: { left: 8 },
  tabArrowRight: { right: 8 },
  tabBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 999, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#FFFFFF' },
  tabBtnActive: { backgroundColor: '#EFF6FF', borderColor: '#2563EB' },
  tabBtnText: { color: '#94A3B8', fontSize: 12, fontWeight: '700' },
  tabBtnTextActive: { color: '#2563EB' },
  tabBtnDisabled: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', opacity: 0.6 },
  tabBtnTextDisabled: { color: '#CBD5E1' },

  // card
  card: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, padding: 16, marginHorizontal: 16, gap: 12 },
  cardTitle: { color: '#0F172A', fontSize: 15, fontWeight: '800' },
  cardCentered: { alignItems: 'center', justifyContent: 'center', paddingVertical: 28, gap: 8 },
  allClear: { color: '#047857', fontSize: 14, fontWeight: '700' },
  emptyStateTitle: { color: '#475569', fontSize: 15, fontWeight: '700' },
  emptyStateSub: { color: '#94A3B8', fontSize: 13, textAlign: 'center' },

  // resumo
  evoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  evoStat: { flex: 1, alignItems: 'center' },
  evoValue: { fontSize: 30, fontWeight: '900', color: '#0F172A' },
  evoLabel: { color: '#64748B', fontSize: 11, fontWeight: '600', marginTop: 2 },
  evoBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  evoBadgeText: { fontSize: 13, fontWeight: '800' },
  evoMeta: { gap: 4, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  evoMetaText: { color: '#64748B', fontSize: 12 },
  evoMetaBold: { color: '#475569', fontWeight: '700' },
  pendingRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pendingDot: { width: 8, height: 8, borderRadius: 4 },
  pendingLabel: { flex: 1, color: '#0F172A', fontSize: 13, fontWeight: '600' },
  pendingCrit: { fontSize: 11, fontWeight: '800' },
  moreText: { color: '#94A3B8', fontSize: 12, textAlign: 'center' },
  textarea: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderRadius: 10, borderWidth: 1, color: '#0F172A', fontSize: 13, minHeight: 64, padding: 10, textAlignVertical: 'top' },
  // skeleton
  skelValue: { backgroundColor: '#E2E8F0', borderRadius: 8, height: 30, width: 54 },
  skelBadge: { backgroundColor: '#CBD5E1', borderRadius: 6, height: 14, width: 56 },
  skelLine: { backgroundColor: '#E2E8F0', borderRadius: 6, height: 13, width: '70%' as const },
  // observation
  obsPreview: { alignItems: 'center', backgroundColor: '#EFF6FF', borderColor: '#BFDBFE', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, paddingHorizontal: 10, paddingVertical: 8 },
  obsPreviewText: { color: '#1E40AF', flex: 1, fontSize: 12 },
  obsBox: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderRadius: 10, borderWidth: 1, gap: 8, padding: 10 },
  obsTextarea: { borderColor: 'transparent', borderRadius: 6, borderWidth: 1, color: '#0F172A', fontSize: 13, minHeight: 72, textAlignVertical: 'top' },
  obsBoxFooter: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  obsBoxFooterRight: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  obsClearBtn: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  obsClearBtnText: { color: '#B91C1C', fontSize: 12, fontWeight: '600' },
  obsCancelBtn: { backgroundColor: '#F1F5F9', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 6 },
  obsCancelBtnText: { color: '#475569', fontSize: 12, fontWeight: '700' },
  obsDoneBtn: { backgroundColor: '#2563EB', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 6 },
  obsDoneBtnText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  // X para remover a foto — canto superior direito da caixa do comentário
  photoRemoveX: { position: 'absolute', top: 5, right: 5, zIndex: 2, width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  // emergency
  emergencyPreview: { alignItems: 'center', backgroundColor: '#FEF2F2', borderColor: '#FECACA', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 8, paddingHorizontal: 10, paddingVertical: 8 },
  emergencyPreviewText: { color: '#DC2626', flex: 1, fontSize: 12, fontWeight: '600' },
  emergencyBox: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderRadius: 10, borderWidth: 1, gap: 8, padding: 10 },
  emergencyTextarea: { borderColor: 'transparent', borderRadius: 6, borderWidth: 1, color: '#0F172A', fontSize: 13, minHeight: 72, textAlignVertical: 'top' },
  // card actions row
  cardActions: { borderTopColor: '#F1F5F9', borderTopWidth: 1, flexDirection: 'row', gap: 4, paddingTop: 8 },
  cardActionBtn: { alignItems: 'center', borderColor: '#E2E8F0', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 6, paddingHorizontal: 8, paddingVertical: 7, flex: 1, justifyContent: 'center' },
  cardActionBtnText: { color: '#64748B', fontSize: 11, fontWeight: '600' },

  // checklist
  checklistGroup: { gap: 10, paddingHorizontal: 16 },
  checklistGroupHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 4 },
  checklistGroupDot: { width: 10, height: 10, borderRadius: 5 },
  checklistGroupTitle: { color: '#0F172A', fontSize: 13, fontWeight: '800', flex: 1 },
  checklistGroupCount: { color: '#94A3B8', fontSize: 11, fontWeight: '600' },
  checklistHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, gap: 8 },
  checklistHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  checklistProgress: { color: '#475569', fontSize: 13, fontWeight: '700' },
  checklistAreaRow: { flexDirection: 'row', gap: 6, paddingHorizontal: 16, paddingBottom: 8 },
  checklistAreaBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 8, borderRadius: 10, backgroundColor: '#F1F5F9' },
  checklistAreaBtnExterior: { backgroundColor: '#FEF3C7' },
  checklistAreaBtnInterior: { backgroundColor: '#E0F2FE' },
  checklistAreaBtnText: { fontSize: 12, fontWeight: '700', color: '#94A3B8' },
  checklistAreaBtnTextExterior: { color: '#B45309' },
  checklistAreaBtnTextInterior: { color: '#0369A1' },
  addStepBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: '#DBEAFE', backgroundColor: '#EFF6FF', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  addStepBtnText: { color: '#2563EB', fontSize: 11, fontWeight: '800' },
  resetBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  resetBtnText: { color: '#64748B', fontSize: 11, fontWeight: '700' },
  checkLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  extraBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#F5F3FF', borderColor: '#DDD6FE', borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 2 },
  extraBadgeText: { color: '#7C3AED', fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
  addStepAreaField: { gap: 6, marginTop: 10 },
  addStepAreaLabel: { color: '#475569', fontSize: 12, fontWeight: '700' },
  addStepAreaRow: { flexDirection: 'row', gap: 8 },
  addStepAreaBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 11, borderRadius: 10, backgroundColor: '#F1F5F9' },
  addStepAreaBtnInt: { backgroundColor: '#0891B2' },
  addStepAreaBtnExt: { backgroundColor: '#D97706' },
  addStepAreaBtnText: { color: '#94A3B8', fontSize: 13, fontWeight: '700' },
  addStepAreaBtnTextActive: { color: '#FFFFFF' },
  removeStepBtn: { padding: 4 },
  checkCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, borderLeftWidth: 4, padding: 14, gap: 12 },
  checkCardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  checkIcon: { width: 38, height: 38, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  checkIconSymbol: { fontSize: 17, fontWeight: '900' },
  checkCardInfo: { flex: 1 },
  checkLabel: { color: '#0F172A', fontSize: 14, fontWeight: '700' },
  checkStatus: { fontSize: 12, fontWeight: '600', marginTop: 6 },
  checkPhotoCount: { color: '#64748B', fontSize: 11, marginTop: 3 },
  stateRow: { flexDirection: 'row', gap: 6 },
  checkCardLocked: { opacity: 0.75, backgroundColor: '#FFFBEB' },
  checkCardIndented: { marginLeft: 20, backgroundColor: '#F0F9FF', borderLeftColor: '#0891B2' },
  checkCardTopMain: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  menuDotsBtn: { padding: 4 },
  assignedWorkersBadge: { color: '#7C3AED', fontSize: 11, fontWeight: '700', marginTop: 2 },
  lockBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#FEF3C7', borderColor: '#FCD34D', borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  lockTitle: { color: '#92400E', fontSize: 12, fontWeight: '800', marginBottom: 2 },
  lockText: { color: '#B45309', fontSize: 12, fontWeight: '600' },

  // group step badge
  groupBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#E0F2FE', borderColor: '#BAE6FD', borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 2 },
  groupBadgeText: { color: '#0891B2', fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },

  // worker assignment picker
  workerPickerSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '88%', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 28, gap: 14 },
  workerPickerHandle: { alignSelf: 'center', width: 40, height: 4, borderRadius: 999, backgroundColor: '#E2E8F0', marginBottom: 2 },
  workerPickerHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  workerPickerTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900' },
  workerPickerSub: { color: '#64748B', fontSize: 12, marginTop: 2 },
  workerSearchWrap: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, minHeight: 44 },
  workerSearchInput: { flex: 1, color: '#0F172A', fontSize: 13, paddingVertical: 10 },
  workerList: { maxHeight: 420 },
  workerEmpty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 32, gap: 8 },
  workerEmptyText: { color: '#475569', fontSize: 14, fontWeight: '700' },
  workerEmptySub: { color: '#94A3B8', fontSize: 12, textAlign: 'center' },
  workerRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderRadius: 12, paddingHorizontal: 4 },
  workerRowSelected: { backgroundColor: '#F5F3FF' },
  workerAvatar: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  workerAvatarText: { fontSize: 15, fontWeight: '900' },
  workerName: { color: '#0F172A', fontSize: 14, fontWeight: '700' },
  workerFuncao: { color: '#64748B', fontSize: 12, marginTop: 1 },
  workerSaveBtn: { backgroundColor: '#6D28D9', borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14 },
  workerSaveBtnText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },

  // roadmap (sub-step progress line)
  roadmapTrack: { flexDirection: 'row', paddingTop: 2 },
  roadmapCell: { flex: 1, alignItems: 'center', gap: 6 },
  roadmapDotRow: { flexDirection: 'row', alignItems: 'center', width: '100%' },
  roadmapHalfLine: { flex: 1, height: 2 },
  roadmapDot: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  roadmapInnerDot: { width: 8, height: 8, borderRadius: 4 },
  roadmapCellLabel: { fontSize: 10, fontWeight: '700', textAlign: 'center', lineHeight: 13 },
  stateBtn: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 8, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#F8FAFC' },
  stateBtnText: { color: '#64748B', fontSize: 11, fontWeight: '700' },

  // status dropdown (progresso da etapa)
  statusSelect: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#F8FAFC' },
  statusSelectOpen: { borderColor: '#CBD5E1', backgroundColor: '#FFFFFF' },
  statusSelectText: { flex: 1, fontSize: 13, fontWeight: '800' },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  statusMenu: { marginTop: 6, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  statusMenuRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 11, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  statusMenuText: { color: '#475569', fontSize: 13, fontWeight: '600' },
  // status como botões — linha horizontal (1 linha), só o nome da etapa
  statusBtnRow: { flexDirection: 'row', gap: 6 },
  statusBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 9, paddingHorizontal: 4, borderRadius: 10, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#F8FAFC' },
  statusBtnLabel: { fontSize: 11, fontWeight: '800', textAlign: 'center', lineHeight: 13 },
  issueBox: { backgroundColor: '#FFFBEB', borderColor: '#FDE68A', borderRadius: 10, borderWidth: 1, padding: 12, gap: 10 },
  issueBoxTitle: { color: '#92400E', fontSize: 12, fontWeight: '800' },
  critRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  critBtn: { borderRadius: 8, borderWidth: 1, borderColor: '#CBD5E1', paddingHorizontal: 10, paddingVertical: 7, backgroundColor: '#FFFFFF' },
  critBtnText: { color: '#475569', fontSize: 12, fontWeight: '700' },
  photoBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderColor: '#DBEAFE', backgroundColor: '#EFF6FF', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, alignSelf: 'flex-start' },
  photoBtnText: { color: '#2563EB', fontSize: 12, fontWeight: '700' },
  thumbGrid: { gap: 10 },
  thumbCard: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  thumbBody: { flex: 1, gap: 6 },
  thumb: { width: 100, height: 80, borderRadius: 8, backgroundColor: '#F1F5F9' },
  thumbOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', gap: 4, backgroundColor: 'rgba(15,23,42,0.55)', borderRadius: 8 },
  thumbOverlayText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  thumbBadge: { position: 'absolute', top: 4, right: 4, width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#047857' },
  thumbLabel: { color: '#64748B', fontSize: 11 },
  thumbInput: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderRadius: 10, borderWidth: 1, color: '#0F172A', fontSize: 13, minHeight: 64, padding: 10, textAlignVertical: 'top' },
  removeBtn: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  removeBtnText: { color: '#B91C1C', fontSize: 11, fontWeight: '700' },

  // pendências
  issueCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, borderLeftWidth: 4, marginHorizontal: 16, padding: 14, gap: 8 },
  issueCardRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, justifyContent: 'space-between' },
  issueCardLabel: { color: '#0F172A', fontSize: 14, fontWeight: '800', flex: 1 },
  issueCardState: { fontSize: 12, fontWeight: '600' },
  issueCardComment: { color: '#475569', fontSize: 13, lineHeight: 18 },
  issueCardPhotos: { color: '#64748B', fontSize: 12 },
  critPill: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 3 },
  critPillText: { fontSize: 11, fontWeight: '800' },
  sectionLabel: { color: '#64748B', fontSize: 12, fontWeight: '800', paddingHorizontal: 16, marginTop: 4 },
  blockedCard: { backgroundColor: '#FFFBEB', borderColor: '#FCD34D', borderWidth: 1, borderRadius: 12, marginHorizontal: 16, padding: 12, gap: 6 },
  blockedRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  blockedService: { color: '#92400E', fontSize: 13, fontWeight: '800', flex: 1 },
  blockedChain: { color: '#B45309', fontSize: 12 },
  impactBadge: { backgroundColor: '#FEF3C7', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  impactBadgeText: { color: '#B45309', fontSize: 11, fontWeight: '800' },

  // fotos
  gallery: { paddingHorizontal: 16, gap: 10 },
  galleryCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, overflow: 'hidden' },
  galleryImage: { width: '100%', height: 200, backgroundColor: '#F1F5F9' },
  galleryInfo: { padding: 12, gap: 4 },
  galleryService: { color: '#0F172A', fontSize: 13, fontWeight: '700' },
  galleryMeta: { color: '#64748B', fontSize: 12 },
  galleryComment: { color: '#475569', fontSize: 13, marginTop: 2 },

  // serviços
  svcRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
  svcRowBorder: { borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  svcStripe: { width: 4, height: 38, borderRadius: 2 },
  svcInfo: { flex: 1, paddingLeft: 10 },
  svcLabel: { color: '#0F172A', fontSize: 13, fontWeight: '700' },
  svcComment: { color: '#64748B', fontSize: 11, marginTop: 2 },
  svcRight: { alignItems: 'flex-end', gap: 4 },
  svcPhotos: { color: '#64748B', fontSize: 11 },
  svcBadge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  svcBadgeText: { fontSize: 11, fontWeight: '800' },

  // cronograma
  alertBox: { backgroundColor: '#FEF3C7', borderColor: '#FCD34D', borderWidth: 1, borderRadius: 10, padding: 12, marginHorizontal: 16 },
  alertText: { color: '#92400E', fontSize: 13, fontWeight: '600' },
  schedCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, marginHorizontal: 16, padding: 14, gap: 12 },
  schedCardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, justifyContent: 'space-between' },
  schedInfo: { flex: 1, gap: 3 },
  schedService: { color: '#0F172A', fontSize: 14, fontWeight: '700' },
  schedInspection: { color: '#64748B', fontSize: 12 },
  schedBadge: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  schedBadgeText: { fontSize: 12, fontWeight: '800' },
  schedNA: { color: '#94A3B8', fontSize: 13 },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  fieldGroup: { flexGrow: 1, gap: 6, minWidth: 140 },
  fieldLabel: { color: '#475569', fontSize: 12, fontWeight: '700' },
  input: { backgroundColor: '#F8FAFC', borderColor: '#CBD5E1', borderRadius: 8, borderWidth: 1, color: '#0F172A', fontSize: 13, minHeight: 42, paddingHorizontal: 10 },
  inputDisabled: { backgroundColor: '#F1F5F9', borderRadius: 8, padding: 10 },
  inputDisabledText: { color: '#94A3B8', fontSize: 13 },
  schedMeta: { gap: 4 },
  schedMetaText: { color: '#475569', fontSize: 12 },
  schedDelay: { color: '#B91C1C', fontSize: 12, fontWeight: '700' },
  schedBlocked: { color: '#B45309', fontSize: 12, fontStyle: 'italic' },

  // medições
  measSummaryRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16 },
  measSumCard: { flex: 1, backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 12, padding: 12, alignItems: 'center', gap: 2 },
  measSumValue: { color: '#0F172A', fontSize: 20, fontWeight: '900' },
  measSumLabel: { color: '#64748B', fontSize: 11, fontWeight: '600' },
  measCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, marginHorizontal: 16, padding: 14, gap: 12 },
  measCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  measService: { color: '#0F172A', fontSize: 14, fontWeight: '800', flex: 1 },
  measTotal: { color: '#94A3B8', fontSize: 16, fontWeight: '900' },
  dupAlert: { backgroundColor: '#FEF3C7', borderRadius: 8, padding: 10 },
  dupAlertText: { color: '#B45309', fontSize: 12, fontWeight: '700' },
  optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  optBtn: { borderRadius: 8, borderWidth: 1, borderColor: '#CBD5E1', paddingHorizontal: 10, paddingVertical: 7 },
  optBtnText: { color: '#475569', fontSize: 12, fontWeight: '700' },
  optBtnActive: { backgroundColor: '#EFF6FF', borderColor: '#2563EB' },
  optBtnTextActive: { color: '#2563EB' },
  optBtnGreen: { backgroundColor: '#D1FAE5', borderColor: '#059669' },
  optBtnGreenText: { color: '#059669' },
  evidenceThumb: { width: 100, height: 80, borderRadius: 8, backgroundColor: '#F1F5F9' },
  primaryBtn: { backgroundColor: '#2563EB', borderRadius: 10, padding: 13, alignItems: 'center' },
  primaryBtnText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  clearBtn: { borderRadius: 8, borderWidth: 1, borderColor: '#E2E8F0', paddingHorizontal: 12, paddingVertical: 8 },
  clearBtnText: { color: '#475569', fontSize: 12, fontWeight: '700' },
  savedMeasCard: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, marginHorizontal: 16, padding: 14, gap: 8 },
  savedMeasTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  savedMeasInfo: { flex: 1, gap: 3 },
  savedMeasService: { color: '#0F172A', fontSize: 13, fontWeight: '800' },
  savedMeasMeta: { color: '#64748B', fontSize: 12 },
  savedMeasTotal: { color: '#047857', fontSize: 16, fontWeight: '900' },
  savedMeasFooter: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignItems: 'center' },
  savedMeasType: { backgroundColor: '#EFF6FF', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  savedMeasTypeText: { color: '#2563EB', fontSize: 11, fontWeight: '700' },
  savedMeasStatus: { backgroundColor: '#D1FAE5', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  savedMeasStatusText: { color: '#047857', fontSize: 11, fontWeight: '700' },
  savedMeasComment: { color: '#64748B', fontSize: 12, fontStyle: 'italic' },

  // histórico
  visitCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 14, marginHorizontal: 16, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  visitCardLeft: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, flex: 1 },
  visitDot2: { width: 10, height: 10, borderRadius: 5, marginTop: 3 },
  visitDate: { color: '#0F172A', fontSize: 13, fontWeight: '700' },
  visitResp: { color: '#64748B', fontSize: 12, marginTop: 2 },
  visitMeta: { color: '#94A3B8', fontSize: 11, marginTop: 2 },
  visitCardRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  visitEvo: { fontSize: 14, fontWeight: '800' },

  // photo source picker
  pickerSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 24, paddingTop: 8 },
  pickerTitle: { textAlign: 'center', fontSize: 15, fontWeight: '700', color: '#0F172A', paddingVertical: 14, paddingHorizontal: 20 },
  pickerOption: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 16, paddingHorizontal: 24 },
  pickerOptionText: { fontSize: 16, color: '#0F172A', fontWeight: '500' },
  pickerDivider: { height: 1, backgroundColor: '#F1F5F9', marginHorizontal: 20 },
  pickerCancel: { marginHorizontal: 20, marginTop: 16, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', paddingVertical: 14, alignItems: 'center' },
  pickerCancelText: { fontSize: 15, color: '#64748B', fontWeight: '600' },

  // modals
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: 'hidden', maxHeight: '88%' },
  modalImage: { width: '100%', height: 260, backgroundColor: '#000' },
  modalInfo: { padding: 16, gap: 4 },
  modalService: { color: '#0F172A', fontSize: 14, fontWeight: '800' },
  modalMeta: { color: '#64748B', fontSize: 12 },
  modalComment: { color: '#475569', fontSize: 13, marginTop: 4 },
  modalClose: { margin: 16, backgroundColor: '#F1F5F9', borderRadius: 12, padding: 14, alignItems: 'center' },
  modalCloseText: { color: '#0F172A', fontSize: 14, fontWeight: '800' },
  visitModalSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '90%' },
  visitModalContent: { padding: 20, gap: 14 },
  visitModalTitle: { color: '#0F172A', fontSize: 18, fontWeight: '900' },
  visitModalGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  visitModalChip: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderWidth: 1, borderRadius: 999, color: '#475569', fontSize: 12, fontWeight: '700', paddingHorizontal: 10, paddingVertical: 6 },
  visitModalSectionTitle: { color: '#0F172A', fontSize: 14, fontWeight: '800' },
  visitModalEmpty: { color: '#94A3B8', fontSize: 13 },
  visitModalItem: { color: '#475569', fontSize: 13 },
  visitModalNote: { color: '#475569', fontSize: 13, fontStyle: 'italic' },

  // add-step modal
  addStepSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%', paddingHorizontal: 22, paddingTop: 10, paddingBottom: 28, gap: 18 },
  addStepGrabber: { alignSelf: 'center', width: 40, height: 4, borderRadius: 999, backgroundColor: '#E2E8F0', marginBottom: 4 },
  addStepHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  addStepHeaderIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EFF6FF' },
  addStepCloseBtn: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F1F5F9' },
  addStepTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900' },
  addStepSub: { color: '#64748B', fontSize: 12, lineHeight: 17, marginTop: 2 },
  addStepSearchWrap: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, minHeight: 44 },
  addStepSearchInput: { flex: 1, color: '#0F172A', fontSize: 13, paddingVertical: 10 },
  addStepList: { maxHeight: 480 },
  addStepEmpty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 28, gap: 8 },
  addStepEmptyText: { color: '#64748B', fontSize: 13, textAlign: 'center' },
  addStepGroup: { gap: 14 },
  addStepGroupHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, paddingHorizontal: 4 },
  addStepGroupDot: { width: 10, height: 10, borderRadius: 5 },
  addStepGroupTitle: { color: '#0F172A', fontSize: 14, fontWeight: '800', flex: 1 },
  addStepGroupCount: { color: '#64748B', fontSize: 12, fontWeight: '700', backgroundColor: '#F1F5F9', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 2, minWidth: 24, textAlign: 'center' },
  addStepItem: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 18, paddingRight: 16, paddingLeft: 0, borderRadius: 14, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#FFFFFF', overflow: 'hidden' },
  addStepItemBullet: { width: 5, alignSelf: 'stretch', backgroundColor: '#E2E8F0' },
  addStepItemName: { color: '#0F172A', fontSize: 15, fontWeight: '700', lineHeight: 20 },
  addStepBadgeRow: { flexDirection: 'row', gap: 6, marginTop: 6 },
  addStepBadge: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 3 },
  addStepBadgeText: { fontSize: 10, fontWeight: '800' },
  addStepPlusBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#2563EB', alignItems: 'center', justifyContent: 'center' },

  // confirm dialogs
  confirmSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 22, gap: 12, alignItems: 'center' },
  confirmIcon: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  confirmTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900', textAlign: 'center' },
  confirmSub: { color: '#475569', fontSize: 13, textAlign: 'center', lineHeight: 18 },
  confirmActions: { flexDirection: 'row', gap: 10, marginTop: 6, alignSelf: 'stretch' },
  confirmBtnGhost: { flex: 1, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', paddingVertical: 13, alignItems: 'center', backgroundColor: '#FFFFFF' },
  confirmBtnGhostText: { color: '#475569', fontSize: 14, fontWeight: '800' },
  confirmBtnDanger: { flex: 1, borderRadius: 12, paddingVertical: 13, alignItems: 'center', backgroundColor: '#B91C1C' },
  confirmBtnDangerText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },

  // back-to-top FAB
  backToTopFab: {
    position: 'absolute', right: 20, width: 44, height: 44, borderRadius: 22,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#64748B',
    shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 6,
  },

  // save toast — pinned above the bottom tab bar
  saveToast: {
    position: 'absolute', left: 24, right: 24, bottom: 24,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    paddingVertical: 10, paddingHorizontal: 18, borderRadius: 999,
    backgroundColor: '#0F172A',
    shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 4,
  },
  saveToastSaved: { backgroundColor: '#047857' },
  saveToastError: { backgroundColor: '#B91C1C' },
  saveToastText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800', letterSpacing: 0.2 },
});

